version: '3.9'
name: "postgres"

services:
  postgres:
    image: postgres:latest
    container_name: "cats-mvc"
    shm_size: 128mb
    environment:
      POSTGRES_DB: cats
      POSTGRES_USER: cat
      POSTGRES_PASSWORD: cat
    ports:
      - "5434:5432"
    volumes:
      - ./dao/src/main/resources/cats.sql:/docker-entrypoint-initdb.d/cats.sql
      - cat_pg_data:/var/lib/postgresql/data

volumes:
  cat_pg_data: